#
# Default values for cpack
#
# Note: this is just default values, you can overload anything in your CMakeLists.txt.
# Note: You will (still) have to call `include(CPack)`

set(CPACK_GENERATOR NSIS)
set(CPACK_VERBATIM_VARIABLES TRUE)
set(CPACK_STRIP_FILES TRUE)

# Installer:
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "CERN SUSoft - BE-GM-APC")

set(CPACK_PACKAGE_VERSION_MAJOR ${EXE_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${EXE_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${EXE_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/../README.md")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/../README.md")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://confluence.cern.ch/display/SUS/Home")

# name of the installer
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(CPACK_SYSTEM_NAME "win64")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
	set(CPACK_SYSTEM_NAME "win32")
endif()
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}Installer-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME})
# set the package header icon for MUI
set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_LIST_DIR}\\SU-icon.ico")

# Directory name in the "Program Files"
set(CPACK_PACKAGE_INSTALL_DIRECTORY "SUSoft\\${CPACK_PACKAGE_NAME}\\${CPACK_PACKAGE_VERSION}")
# Elements of the menu start folder
set(CPACK_PACKAGE_EXECUTABLES ${CPACK_PACKAGE_NAME} "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")

# Components
set(CPACK_COMPONENTS_ALL application documentation libraries)
# Registry
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_HKLM_REGISTRY_KEY "${CPACK_PACKAGE_NAME}\\${CPACK_PACKAGE_VERSION}")

# NSIS specific
set(CPACK_NSIS_MODIFY_PATH TRUE)
# infos
set(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
set(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
set(CPACK_NSIS_HELP_LINK "https://confluence.cern.ch/display/SUS/User+Guides")
set(CPACK_NSIS_URL_INFO_ABOUT "https://confluence.cern.ch/display/SUS/User+Guides")
set(CPACK_NSIS_CONTACT "susoft.support@cern.ch")
# Icon in the add/remove control panel. Must be an .exe file 
set(CPACK_NSIS_INSTALLED_ICON_NAME ${CPACK_COMPONENT_APPLICATION_DISPLAY_NAME}.exe)
# Set installer icon (need .ico !!!)
set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_LIST_DIR}\\SU-icon.ico")
set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_LIST_DIR}\\SU-icon.ico")
# Create desktop icon
set(CPACK_CREATE_DESKTOP_LINKS ${CPACK_PACKAGE_NAME})

set(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
set(CPACK_NSIS_DEFINES "!define MUI_STARTMENUPAGE_DEFAULTFOLDER \"${CPACK_PACKAGE_INSTALL_DIRECTORY}\"")

set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
	ExecWait '\"$INSTDIR\\${VCREDIST_INSTALLER_NAME}\" /install /quiet /norestart'
	WriteRegStr HKLM 'SOFTWARE\\${CPACK_PACKAGE_VENDOR}\\${CPACK_PACKAGE_HKLM_REGISTRY_KEY}' 'Path' '$INSTDIR'
	WriteRegStr HKLM 'SOFTWARE\\${CPACK_PACKAGE_VENDOR}\\${CPACK_PACKAGE_HKLM_REGISTRY_KEY}' 'Product Name' '${CPACK_PACKAGE_DESCRIPTION_SUMMARY}'
	WriteRegStr HKLM 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${CPACK_PACKAGE_INSTALL_REGISTRY_KEY}' 'DisplayName' '${CPACK_PACKAGE_INSTALL_REGISTRY_KEY}'
	WriteRegStr HKLM 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${CPACK_PACKAGE_INSTALL_REGISTRY_KEY}' 'Publisher' '${CPACK_PACKAGE_VENDOR}'
")

SET(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
	DeleteRegKey HKLM 'SOFTWARE\\${CPACK_PACKAGE_VENDOR}\\${CPACK_PACKAGE_HKLM_REGISTRY_KEY}'
	Delete \"$SMPROGRAMS\\$STARTMENU_FOLDER\\Helpfile.lnk\"
	Delete \"$SMPROGRAMS\\$STARTMENU_FOLDER\\OnlineHelp.lnk\"
")
